CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(1000),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    cuisine VARCHAR(500),
    rating DOUBLE PRECISION NOT NULL,
    review_count INTEGER,
    time VARCHAR(50),
    discount VARCHAR(50),
    image VARCHAR(1000),
    logo VARCHAR(500),
    category VARCHAR(50),
    verified BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    is_open BOOLEAN NOT NULL,
    accepting_orders BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
    id VARCHAR(20) PRIMARY KEY,
    category_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    image VARCHAR(500),
    filter VARCHAR(50),
    count VARCHAR(100),
    active BOOLEAN NOT NULL,
    display_order INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_active ON users (active);
CREATE INDEX IF NOT EXISTS idx_restaurant_id ON restaurants (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_category ON restaurants (category);
CREATE INDEX IF NOT EXISTS idx_active_restaurant ON restaurants (active);
CREATE INDEX IF NOT EXISTS idx_category_id ON categories (category_id);
CREATE INDEX IF NOT EXISTS idx_active_category ON categories (active);
CREATE INDEX IF NOT EXISTS idx_filter_category ON categories (filter);
