CREATE TABLE IF NOT EXISTS user_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan_code VARCHAR(40) NOT NULL,
    plan_name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    monthly_price DOUBLE PRECISION NOT NULL,
    discount_percent INTEGER NOT NULL,
    max_discount_per_order DOUBLE PRECISION NOT NULL,
    min_order_for_free_delivery DOUBLE PRECISION NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    auto_renew BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    next_billing_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uq_user_subscriptions_user UNIQUE (user_id),
    CONSTRAINT fk_user_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_subscription_user ON user_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscription_active ON user_subscriptions(user_id, active);
